# Overlunky hotkeys
# Syntax:
# function = keycode_in_hex
# For modifiers, add 0x100 for Ctrl, 0x200 for Shift and 0x800 for Alt
# For mouse buttons, add 0x400
# For Mouse wheel, 0x11 = down, 0x12 = up
# Set to 0x0 to disable key
# Example: G is 0x47, so Ctrl+G is 0x147, 0x402 is Mouse2 etc
# Get more hex keycodes from https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
# If you mess this file up, you can just delete it and run overlunky to get the defaults back
[hotkeys]
camera_down              = 0x24b     # Shift+K
camera_left              = 0x24a     # Shift+J
camera_reset             = 0x255     # Shift+U
camera_right             = 0x24c     # Shift+L
camera_up                = 0x249     # Shift+I
change_layer             = 0x209     # Shift+Tab
clear_messages           = 0x108     # Ctrl+BackSpace
close_console            = 0x1b      # Escape
console                  = 0xc0      # `
console_alt              = 0xdc      # \
destroy_grabbed          = 0x2e      # Delete
destroy_selected         = 0x82e     # Alt+Delete
detach_tab               = 0x344     # Ctrl+Shift+D
enter                    = 0xd       # Return
escape                   = 0x1b      # Escape
export_void              = 0x145     # Ctrl+E
frame_advance            = 0x20      # space
frame_advance_alt        = 0x220     # Shift+space
hide_ui                  = 0x7a      # F11
hotbar_0                 = 0x30      # 0
hotbar_1                 = 0x31      # 1
hotbar_2                 = 0x32      # 2
hotbar_3                 = 0x33      # 3
hotbar_4                 = 0x34      # 4
hotbar_5                 = 0x35      # 5
hotbar_6                 = 0x36      # 6
hotbar_7                 = 0x37      # 7
hotbar_8                 = 0x38      # 8
hotbar_9                 = 0x39      # 9
import_void              = 0x156     # Ctrl+V
load_settings            = 0x34c     # Ctrl+Shift+L
load_state_1             = 0x270     # Shift+F1
load_state_2             = 0x271     # Shift+F2
load_state_3             = 0x272     # Shift+F3
load_state_4             = 0x273     # Shift+F4
mouse_big_boom           = 0x0       # Disabled
mouse_blast              = 0x0       # Disabled
mouse_boom               = 0x0       # Disabled
mouse_camera_drag        = 0x404     # Mouse4
mouse_clone              = 0x0       # Disabled
mouse_decorate           = 0xc04     # Alt+Mouse4
mouse_destroy            = 0x405     # Mouse5
mouse_destroy_unsafe     = 0x605     # Shift+Mouse5
mouse_draw               = 0xc01     # Alt+Mouse1
mouse_erase              = 0xc05     # Alt+Mouse5
mouse_grab               = 0x403     # Mouse3
mouse_grab_throw         = 0x503     # Ctrl+Mouse3
mouse_grab_throw_unsafe  = 0x703     # Ctrl+Shift+Mouse3
mouse_grab_unsafe        = 0x603     # Shift+Mouse3
mouse_nuke               = 0x0       # Disabled
mouse_select             = 0xc03     # Alt+Mouse3
mouse_select_unsafe      = 0xe03     # Alt+Shift+Mouse3
mouse_spawn              = 0x401     # Mouse1
mouse_spawn_over         = 0x501     # Ctrl+Mouse1
mouse_spawn_throw        = 0x401     # Mouse1
mouse_teleport           = 0x402     # Mouse2
mouse_teleport_throw     = 0x402     # Mouse2
mouse_zap                = 0x0       # Disabled
mouse_zoom_in            = 0x512     # Ctrl+WheelUp
mouse_zoom_out           = 0x511     # Ctrl+WheelDown
move_down                = 0x28      # Down
move_left                = 0x25      # Left
move_pagedown            = 0x22      # Next
move_pageup              = 0x21      # Prior
move_right               = 0x27      # Right
move_up                  = 0x26      # Up
peek_layer               = 0x8       # BackSpace
quick_camp               = 0x143     # Ctrl+C
quick_restart            = 0x151     # Ctrl+Q
quick_restart_seed       = 0x851     # Alt+Q
quick_start              = 0x51      # Q
reload_enabled_scripts   = 0x174     # Ctrl+F5
reset_windows            = 0x352     # Ctrl+Shift+R
respawn                  = 0x152     # Ctrl+R
save_settings            = 0x353     # Ctrl+Shift+S
save_state_1             = 0x274     # Shift+F5
save_state_2             = 0x275     # Shift+F6
save_state_3             = 0x276     # Shift+F7
save_state_4             = 0x277     # Shift+F8
spawn_entity             = 0x10d     # Ctrl+Return
spawn_kit_1              = 0x231     # Shift+1
spawn_kit_2              = 0x232     # Shift+2
spawn_kit_3              = 0x233     # Shift+3
spawn_kit_4              = 0x234     # Shift+4
spawn_kit_5              = 0x235     # Shift+5
spawn_kit_6              = 0x236     # Shift+6
spawn_kit_7              = 0x237     # Shift+7
spawn_kit_8              = 0x238     # Shift+8
spawn_kit_9              = 0x239     # Shift+9
spawn_layer_door         = 0x20d     # Shift+Return
spawn_warp_door          = 0x30d     # Ctrl+Shift+Return
speedhack_10pct          = 0x331     # Ctrl+Shift+1
speedhack_20pct          = 0x332     # Ctrl+Shift+2
speedhack_30pct          = 0x333     # Ctrl+Shift+3
speedhack_40pct          = 0x334     # Ctrl+Shift+4
speedhack_50pct          = 0x335     # Ctrl+Shift+5
speedhack_60pct          = 0x336     # Ctrl+Shift+6
speedhack_70pct          = 0x337     # Ctrl+Shift+7
speedhack_80pct          = 0x338     # Ctrl+Shift+8
speedhack_90pct          = 0x339     # Ctrl+Shift+9
speedhack_decrease       = 0x322     # Ctrl+Shift+Next
speedhack_increase       = 0x321     # Ctrl+Shift+Prior
speedhack_normal         = 0x330     # Ctrl+Shift+0
speedhack_slow           = 0x22      # Next
speedhack_turbo          = 0x21      # Prior
switch_ui                = 0x7b      # F12
toggle_disable_pause     = 0x350     # Ctrl+Shift+P
toggle_entity_info       = 0x345     # Ctrl+Shift+E
toggle_entity_tooltip    = 0x359     # Ctrl+Shift+Y
toggle_flymode           = 0x346     # Ctrl+Shift+F
toggle_ghost             = 0x14f     # Ctrl+O
toggle_godmode           = 0x147     # Ctrl+G
toggle_grid              = 0x347     # Ctrl+Shift+G
toggle_hitboxes          = 0x348     # Ctrl+Shift+H
toggle_hotbar            = 0x342     # Ctrl+Shift+B
toggle_hud               = 0x148     # Ctrl+H
toggle_lights            = 0x14c     # Ctrl+L
toggle_mouse             = 0x14d     # Ctrl+M
toggle_noclip            = 0x146     # Ctrl+F
toggle_pause             = 0x120     # Ctrl+space
toggle_snap              = 0x153     # Ctrl+S
toggle_speedhack_auto    = 0x354     # Ctrl+Shift+T
toggle_uncapped_fps      = 0x355     # Ctrl+Shift+U
toggle_void              = 0x856     # Alt+V
tool_camera              = 0x72      # F3
tool_debug               = 0x37b     # Ctrl+Shift+F12
tool_door                = 0x71      # F2
tool_entity              = 0x70      # F1
tool_entity_properties   = 0x73      # F4
tool_finder              = 0x76      # F7
tool_game_properties     = 0x74      # F5
tool_keys                = 0x34b     # Ctrl+Shift+K
tool_metrics             = 0x349     # Ctrl+Shift+I
tool_options             = 0x78      # F9
tool_save                = 0x75      # F6
tool_script              = 0x77      # F8
tool_style               = 0x355     # Ctrl+Shift+U
warp                     = 0x157     # Ctrl+W
warp_next_level_a        = 0x141     # Ctrl+A
warp_next_level_b        = 0x142     # Ctrl+B
zoom_2x                  = 0x132     # Ctrl+2
zoom_3x                  = 0x133     # Ctrl+3
zoom_4x                  = 0x134     # Ctrl+4
zoom_5x                  = 0x135     # Ctrl+5
zoom_auto                = 0x130     # Ctrl+0
zoom_in                  = 0x1bc     # Ctrl+,
zoom_out                 = 0x1be     # Ctrl+.
zoom_reset               = 0x131     # Ctrl+1

[options] # 0 or 1 unless stated otherwise (default state of options)
borders = 0
camera_hack = 0
console_alt_keys = 0
console_script_messages = 0
disable_achievements = 1
disable_ghost_timer = 0
disable_pause = 0
disable_savegame = 1
docking_with_shift = 1
draw_entity_info = 0
draw_entity_tooltip = 0
draw_grid = 0
draw_hitboxes = 0
draw_hitboxes_interpolated = 1
draw_hotbar = 1
draw_hud = 1
draw_script_messages = 1
enable_unsafe_scripts = 1
fade_script_messages = 1
fly_mode = 0
god_mode = 0
god_mode_companions = 0
hd_cursor = 1
inverted = 0
keyboard_control = 1
lights = 0
load_packs = 1
load_scripts = 0
menu_ui = 0
modifiers_clear_input = 1
mouse_control = 1
multi_viewports = 0
noclip = 0
pause_last_instance = 1
pause_update_camera = 1
show_tooltips = 1
skip_fades = 0
smooth_camera = 1
snap_to_grid = 0
spawn_floor_decorated = 1
speedhack = 0
uncap_unfocused_fps = 1
update_check = 0
vsync = 1
warp_increments_level_count = 1
warp_transition = 1
hue = 0.63 # float, 0.0 - 1.0
saturation = 0.66 # float, 0.0 - 1.0
lightness = 0.66 # float, 0.0 - 1.0
alpha = 1.00 # float, 0.0 - 1.0
scale = 1.00 # float, 0.3 - 2.0
camera_speed = 1.00 # float
pause_type = 0x40 # 64bit flags
pause_ignore_screen = 0x0 # 64bit flags
pause_ignore_screen_trigger = 0x0 # 64bit flags
pause_trigger = 0x0 # 64bit flags
pause_screen = 0x0 # 64bit flags
unpause_trigger = 0x0 # 64bit flags
unpause_screen = 0x0 # 64bit flags
modifiers_block = 0x0 # 32bit flags
kits = []
hotbar = [0] # array of numeric ent types
font_file = "" # string, "file.ttf" or empty to use the embedded font "Hack"
font_size = [
  14.00,
  32.00,
  72.00
] # [ small/ui, medium/messages, big ]
# Script filenames to load automatically on start. Example: autorun_scripts = ["foo.lua", "bar.lua"]
autorun_scripts = [
  "main.lua"
]
# Directory where the scripts are loaded from. You can use relative or absolute path.
# A relative path is relative to the game directory. Use forward / slashes.
script_dir = "Mods/Packs/spelunky2rl/lua"
tabs_open = [
  "tool_camera",
  "tool_door",
  "tool_entity",
  "tool_entity_properties",
  "tool_finder",
  "tool_game_properties"
]
tabs_detached = []
tab_active = "tool_script"
