[general_settings]
enable_loose_file_warning=true
enable_raw_string_loading=false
disable_asset_caching=false
block_save_game=false
allow_save_game_mods=true
use_playlunky_save=false
disable_steam_achievements=false
speedrun_mode=false
font_file="default"
font_file_ru="default"
font_file_jp="default"
font_file_ko="default"
font_file_zhcn="default"
font_file_zhtw="default"
font_file_emoji="default"
font_scale=1.0

[script_settings]
enable_developer_mode=false
enable_developer_console=false
console_history_size=20

[audio_settings]
enable_loose_audio_files=true
cache_decoded_audio_files=false
synchronous_update=true

[sprite_settings]
random_character_select=false
# Makes sure that related files, e.g. char_black.png and char_black.json are always loaded from the same mod
link_related_files=true
generate_character_journal_stickers=true
generate_character_journal_entries=true
generate_sticker_pixel_art=true
enable_sprite_hot_loading=false
# Increase this value if you experience crashes when a sprite is reloaded
sprite_hot_load_delay=400
# Enables the customizable sprite sheets feature, does not work in speedrun mode
enable_customizable_sheets=true
# Scales luminance of customized images based on the color
enable_luminance_scaling=true

[bug_fixes]
# Adds textures for the missing jungle thorns configurations
missing_thorns=true
# May cause issues in multiplayer. Adds textures for the missing sunken city pipes configurations and makes those pipes work, some requiring user input
missing_pipes=false

[key_bindings]
# Default 0xc0 == ~ for US
console=0xc0
# Default 0xdc == \ for US
console_alt=0xdc
# Default 0x1b == ESC
console_close=0x1b

